# Generated by Django 5.2.8 on 2025-11-26 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='챌린지')),
                ('content', models.CharField(max_length=100, verbose_name='설명')),
                ('current_member', models.PositiveIntegerField(default=1, verbose_name='현재 인원')),
                ('max_member', models.PositiveIntegerField(verbose_name='최대 인원')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='목표 인증 횟수')),
                ('type', models.CharField(choices=[('personal', '개인'), ('group', '단체')], max_length=20, verbose_name='챌린지 종류(인원)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading_challenge', to=settings.AUTH_USER_MODEL, verbose_name='챌린지 장')),
                ('members', models.ManyToManyField(blank=True, related_name='joined_challenges', to=settings.AUTH_USER_MODEL, verbose_name='챌린지 참여자들')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verifications/', verbose_name='인증 이미지')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='인증 일시')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='app.challenge', verbose_name='챌린지')),
                ('verified_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='인증한 사람')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
