# Generated by Django 5.2.8 on 2025-11-19 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='master',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='user',
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='챌린지 카테고리'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='챌린지 일정(요일/날짜)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='목표 인증 횟수'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='current_member',
            field=models.PositiveIntegerField(default=1, verbose_name='현재 인원'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leading_challenge', to=settings.AUTH_USER_MODEL, verbose_name='챌린지 장'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='max_member',
            field=models.PositiveIntegerField(default=1, verbose_name='최대 인원'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_challenges', to=settings.AUTH_USER_MODEL, verbose_name='챌린지 참여자들'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='private_password',
            field=models.CharField(blank=True, max_length=50, verbose_name='비공개 비밀번호'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('personal', '개인'), ('group', '단체')], default='group', max_length=20, verbose_name='챌린지 종류(인원)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='verification',
            name='verified_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='인증한 사람'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='content',
            field=models.TextField(verbose_name='챌린지 설명'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=100, verbose_name='챌린지 제목'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='app.challenge', verbose_name='챌린지'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='인증 일시'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='image',
            field=models.ImageField(upload_to='verifications/', verbose_name='인증 이미지'),
        ),
        migrations.DeleteModel(
            name='ChallengeParticipant',
        ),
    ]
