# Generated by Django 5.2.8 on 2025-11-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
