# Generated by Django 5.2.8 on 2025-12-04 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="챌린지 제목")),
                ("content", models.TextField(verbose_name="챌린지 설명")),
                (
                    "current_member",
                    models.PositiveIntegerField(default=1, verbose_name="현재 인원"),
                ),
                (
                    "max_member",
                    models.PositiveIntegerField(default=1, verbose_name="최대 인원"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("personal", "개인"), ("group", "단체")],
                        default="group",
                        max_length=20,
                        verbose_name="챌린지 종류(인원)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("study", "학습"),
                            ("workout", "운동/건강"),
                            ("reading", "독서/기록"),
                            ("habit", "생활습관"),
                            ("hobby", "취미/창작"),
                            ("mind", "멘탈"),
                        ],
                        default="coding",
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="공개 여부"),
                ),
                (
                    "private_password",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="비공개 비밀번호"
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="목표 인증 횟수"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leading_challenge",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="챌린지 장",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_challenges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="챌린지 참여자들",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="응원의 한마디")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="app.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_image", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="verifications/", verbose_name="인증 이미지"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="인증 일시"),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="app.challenge",
                        verbose_name="챌린지",
                    ),
                ),
                (
                    "verified_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="인증한 사람",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
