# Generated by Django 5.2.8 on 2025-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_userprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="category",
            field=models.CharField(
                choices=[
                    ("study", "학습"),
                    ("workout", "운동/건강"),
                    ("reading", "독서/기록"),
                    ("habit", "생활습관"),
                    ("hobby", "취미/창작"),
                    ("mind", "멘탈"),
                ],
                default="study",
                max_length=20,
                verbose_name="카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
