# Generated by Django 5.2.8 on 2025-11-18 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('max_members', models.IntegerField(default=10, verbose_name='최대 인원')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenge_thumbs/')),
                ('category', models.CharField(choices=[('study', '학습'), ('workout', '운동/건강'), ('reading', '독서/기록'), ('habit', '생활습관'), ('hobby', '취미/창작'), ('mind', '멘탈')], default='coding', max_length=20, verbose_name='카테고리')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
